// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.github.springroo.createupdate.domain;

import com.github.springroo.createupdate.domain.PartnerIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PartnerIntegrationTest_Roo_Configurable {
    
    declare @type: PartnerIntegrationTest: @Configurable;
    
}
